apiVersion: reforma.prosimcorp.com/v1alpha1
kind: Patch
metadata:
  name: patch-sample
spec:
  # Synchronization parameters
  synchronization:
    time: "5s"

  # Sources to look for the data to make wonderful patches
  sources:
    - apiVersion: v1
      kind: ConfigMap
      name: cluster-info
      namespace: default

    - apiVersion: v1
      kind: ConfigMap
      name: namespace-info
      namespace: default

  # Target to apply patches to
  target:
    apiVersion: v1
    kind: ConfigMap
    name: my-deployment-something
    namespace: default

  # You know, the patch type
  patchType: application/json-patch+json

  # Templating section is where you can be creative to craft a patch
  # Basically, if you know Helm templating and Kustomize patches, do what you want
  template: |
    {{- $target := (index . 0) -}}
    {{- $source_one := (index . 1) -}}
    {{- $source_two := (index . 2) -}}

    - op: add
      path: /metadata/annotations/cluster-name
      value: "{{- $source_one.metadata.name -}}"
